### PR TITLE
Add argument for custom domain

### PR DESCRIPTION
**Pull request by dan-hanlon**
I saw this was an issue for others as well (#12) so thought I'd look at trying to implement it.

This seems like it should work for me but I'm not an expert on Github Actions. It adds an optional argument for a custom URL, if the argument is empty it should be ignored, if it is set it should overwrite the pages URL.

I haven't tested it comprehensively yet but wanted to get feedback on if this is the right direction.

### CODE REVIEW

**Comment by dan-hanlon** [comment]
Had a chance to look at this again. I've inverted the URL setting so custom url always takes priority if it's set.
My empty string check was wrong but I've fixed that, tested on our repo, and it works.

**Comment by rossjrw** [comment]
Thanks @dan-hanlon, I appreciate your effort! I'll take a thorough look at this when I get the chance.

**Review by voracious — COMMENTED** [review]
Hi @rossjrw. I'm just doing a passing review, as I would also love to use this feature.

The implementation in this PR definitely looks like it would solve my use case. I love the idea of automatically checking the `CNAME` file in the repo, but I also don't mind having to specify the domain in the workflow if that means we can get it sooner.

**Comment by rossjrw** [comment]
Thanks @voracious, appreciate your input.

Agreed, this does look solid. I've added a spot of documentation. Let me know how this works for you @voracious @dan-hanlon?

**Comment by voracious** [comment]
Hey @rossjrw. I'm trying to verify this, but my workflow isn't picking up `v1.3.0` for some reason. Has the latest version been published?

**Comment by voracious** [comment]
To follow up, it looks like it works correctly when explicitly setting the version to `v1.3.0` but not when setting it to `v1`.

**Comment by rossjrw** [comment]
Agh! Silly me - I pushed v1.3.0 but forgot to update v1 (and add v1.3). I'll get onto that...

**Comment by voracious** [comment]
Ah, that explains it. Thanks so much for releasing this. It's been working well for the past week.

**Pull request merged**
